---
- name: Installer et configurer le Master K3s
  hosts: master
  become: yes
  tasks:
    - name: Télécharger et installer K3s (Master)
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Vérifier que le service k3s est lancé
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Récupérer le token du cluster K3s
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      
    - name: Sauvegarder le token au format texte (sur la machine Ansible locale)
      local_action: 
        module: copy
        content: "{{ k3s_token['content'] | b64decode | trim }}"
        dest: "./k3s_token.txt"
      become: no

    - name: Lire le fichier de config kubeconfig
      slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_content

    - name: Sauvegarder et modifier Kubeconfig (sur la machine Ansible locale)
      local_action: 
        module: copy
        content: "{{ kubeconfig_content['content'] | b64decode | replace('127.0.0.1', ansible_host) }}"
        dest: "./k3s_kubeconfig"
      become: no
